function d_dist = get_quartet_dist(d_quartet)
if size(d_quartet,1) == 4; d_quartet = d_quartet'; end;

% d_in columns WT; A; B; AB
% d_out columns WT-AB; WT-A; WT-B; AB-A; AB-B; A-B
d_dist = [ ...
    eu_dist(d_quartet(:,1),d_quartet(:,4)), ...
    eu_dist(d_quartet(:,1),d_quartet(:,2)), ...
    eu_dist(d_quartet(:,1),d_quartet(:,3)), ...
    eu_dist(d_quartet(:,4),d_quartet(:,2)), ...
    eu_dist(d_quartet(:,4),d_quartet(:,3)), ...
    eu_dist(d_quartet(:,2),d_quartet(:,3)), ...
];

